version: '3'
services:
    web:
        image: my-laravel-image
        ports:
            - 8000
        volumes:
            - './:/app'
        networks:
            - mahdi
    db:
        image: 'mysql:5.7'
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - mahdi
    redis:
        image: 'redis:alpine'
        ports:
            - 6379
        networks:
            - mahdi
    nginx:
        image: 'nginx:alpine'
        ports:
            - '8080:8080'
        volumes:
            - './nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - mahdi
networks:
    mahdi:
        driver: bridge
